### ISSUE TITLE
Add key path subscript support

### ISSUE THREAD

**Issue by ryanmasondavies** [kateinoigakukun/StubKit#6]
It would be great to be able to mutate a stub using key path subscripting.

At the moment mutation looks like this:

```
let post = try Stub.make(Post.self) {
	$0.set(\.id, value: 123)
}
```

With key path subscripting, it could look like this:

```
let post = try Stub.make(Post.self) {
	$0[\.id] = 123
}
```

I'm happy to propose this enhancement formally with a pull request, but is there any appetite for it before I do?

**Comment by kateinoigakukun** [comment]
Thanks for your proposal.
Hmm, `subscript` needs to provide a getter, but injector can't get property.

**Comment by ryanmasondavies** [comment]
Ahh, I forgot it’s not possible to make a set-only subscript. Thanks for checking, I’ll close this 🙂
