### ISSUE TITLE
Fails on property wrappers

### ISSUE THREAD

**Issue by ryanmasondavies** [kateinoigakukun/StubKit#8]
This code does not work for properties annotated with property wrappers:

https://github.com/kateinoigakukun/StubKit/blob/33c9dfa6a049840dfd082f5ebbaf434e43df6549/Sources/StubKit/Injector.swift#L15-L26

I'm not sure what could be done about this, as the issue seems to be that MemoryLayout.offset doesn't work for property wrappers, but wanted to flag it for awareness.

**Comment by kateinoigakukun** [comment]
read-only property wrapper like below can't be accessed dynamically, so it's impossible to inject value.

```swift
@propertyWrapper
struct ReadOnly: Decodable {
    let wrappedValue: Int
}
```

But if the property wrapper is mutable, we can create `WritableKeyPath` and it can access field dynamically. I added `Injector.set` overload for WritableKeyPath and it solves this issue partially.

https://github.com/kateinoigakukun/StubKit/commit/35816dfb9eb9c6d8d40b808a1ae9e9c17d6c7456
